#SingleInstance Force
getAllNames()
{
dirIni := "C:\Users\marcu\Desktop\diablo\aspects.ini"
	allNames := [
		["Ghost Walker", IniRead(dirIni, "ALL", "Ghost Walker"),
			"* While Unstoppable and for 4 seconds after, you gain 404404% [10- 25%] increased Movement Speed and can move freely through enemies."],
		["Wind Striker", IniRead(dirIni, "ALL", "Wind Striker"),
			"* Critical Strikes grant 404404.404% [8.0-16.0]% Movement Speed for 1 second, up to 6 seconds."],
		["Shared Misery", IniRead(dirIni, "ALL", "Shared Misery"),
			"* Lucky Hit: When you hit a Crowd Controlled enemy, there is up to a 404404% [30-50]% chance for that Crowd Control effect to spread to another unaffected enemy."],
		["Umbral", IniRead(dirIni, "ALL", "Umbral"),
			"* Restore [1-4] resource of your Primary Resource when you Crowd Control an enemy."],
		["Edgemaster", IniRead(dirIni, "ALL", "Edgemaster"),
			"* Skills deal up to 404404% [10- 20%] increased damage based on your available Primary Resource when cast, receiving the maximum benefit while you have full Primary Resource."],
		["Rapid", IniRead(dirIni, "ALL", "Rapid"),
			"* Basic Skills gain 404404% [15-30%] Attack Speed."],
		["Needle Flare", IniRead(dirIni, "ALL", "Needle Flare"),
			"* Thorns damage dealt has a 404404% [20-40%] chance to deal damage to all enemies around you."],
		["Inner Calm", IniRead(dirIni, "ALL", "Inner Calm"),
			"* Deal 404404% [5.0-10]%[x] increased damage for each second you stand still, up to 30%[x]."],
		["Expectant", IniRead(dirIni, "ALL", "Expectant"),
			"* Attacking enemies with a Basic Skill increases the damage of your next Core Skill cast by 404404% [5-10]% up to 30%."],
		["Retribution", IniRead(dirIni, "ALL", "Retribution"),
			"* Distant enemies have a 8% chance to be Stunned for 2 seconds when they hit you. You deal 404404% [20-40]%[x] increased damage to Stunned enemies."],
		["Might", IniRead(dirIni, "ALL", "Might"),
			"* Basic Skills grant 20% Damage Reduction for [2.0-6.0] seconds."],
		["Disobedience", IniRead(dirIni, "ALL", "Disobedience"),
			"* You gain 404.404404% [0.25-0.50]%[x] increased Armor for 4 seconds when you deal any form of damage, stacking up to 404404.404404% [25.00-50.00]%[x]"],
		["Deflecting Barrier", IniRead(dirIni, "ALL", "Deflecting Barrier"),
			"* While you have a Barrier active, there is a 404404% [7-13]% chance to ignore incoming direct damage from Distant enemies."],
		["Eluding", IniRead(dirIni, "ALL", "Eluding"),
			"* Becoming Injured while Crowd Controlled grants you Unstoppable for 4 seconds. This effect has a [40-20] second Cooldown."],
		["Protector", IniRead(dirIni, "ALL", "Protector"),
			"* Damaging an Elite enemy grants you a Barrier absorbing up to [404] damage for 10 seconds. This effect can only happen once every 30 seconds."],
		["Crowded Sage", IniRead(dirIni, "ALL", "Crowded Sage"),
			"* You Heal for [404] Life per second for each Close enemy, up to [404] Life per second."],
		["Protecting", IniRead(dirIni, "ALL", "Protecting"),
			"* When hit while not Healthy, a magical bubble is summoned around you for [3.0-5.0] seconds. While standing in the bubble players are Immune. Can only occur once every 90 seconds"],
		["Accelerating", IniRead(dirIni, "ALL", "Accelerating"),
			"* Critical Strikes with Core Skills increase your Attack Speed by 404404% [15-25]% for 5 seconds."],
		["Conceited", IniRead(dirIni, "ALL", "Conceited"),
			"* Deal 404404% [15-25%] increased damage while you have a Barrier active."],
		["Smiting", IniRead(dirIni, "ALL", "Smiting"),
			"* You have 404404% [10-20%] increased Critical Strike Chance against Injured enemies. While you are Healthy, you gain 404404% [20- 40%] increased Crowd Control Duration."],
		["Assimilation", IniRead(dirIni, "ALL", "Assimilation"),
			"* You have 8% increased Dodge Chance versus enemies affected by Damage Over Time effects. When you Dodge you gain [5-10] of your Primary Resource."],
		["Starlight", IniRead(dirIni, "ALL", "Starlight"),
			"* Gain [10-20] of your Primary Resource for every 25% of your Life that you Heal."],
		["Exploiter", IniRead(dirIni, "ALL", "Exploiter"),
			"* You have 20% increased Crowd Control Duration. While enemies are Unstoppable, you deal 404404% [20-50%]."]
	]
	return allNames
}