#SingleInstance Force

getNecromancerNames()
{
dirIni := "C:\Users\marcu\Desktop\diablo\aspects.ini"
	necromancerNames := [
		["Bursting Bones", IniRead(dirIni, "NECROMANCER", "Bursting Bones"), 
			"* When a segment of Bone Prison is destroyed or expired, it deals [X] damage in an area around itself."],
		["Decay", IniRead(dirIni, "NECROMANCER", "Decay"), 
			"* Each time the Shadowblight Key Passive deals damage to enemies, it increases the next Shadowblight's damage within xx seconds by [20-40]%[x], stacking up to 5 times."],
		["Empowering Reaper", IniRead(dirIni, "NECROMANCER", "Empowering Reaper"), 
			"* Critical Strikes from Sever have a [10-20]% chance to spawn a pool of Blight under the target that deals [20-60]% bonus damage. This effect can only happen once every 3 seconds."],
		["Explosive Mist", IniRead(dirIni, "NECROMANCER", "Explosive Mist"), 
			"* Blood Mist triggers Corpse Explosion on surrounding Corpses. When Blood Mist detonates a Corpse, its Cooldown is reduced by [0.2-0.5] seconds."],
		["Exposed Flesh", IniRead(dirIni, "NECROMANCER", "Exposed Flesh"), 
			"* Lucky Hit: Up to a 10% chance to generate [30-50] Essence when hitting a Vulnerable enemy with your Bone Skills."],
		["Frenzied Dead", IniRead(dirIni, "NECROMANCER", "Frenzied Dead"), 
			"* Each time one of your Summoning Minions damages an enemy, they gain [10-14]%[+] Attack Speed for 3 seconds, up to [30-42]%[+]"],
		["Grasping Veins", IniRead(dirIni, "NECROMANCER", "Grasping Veins"), 
			"* Gain [10-20]%[+] increased Critical Strike Chance for 6 seconds when you cast Corpse Tendrils. You deal [30-60]%[x] bonus Critical Strike Damage to enemies damaged by Corpse Tendrils."],
		["Hardened Bones", IniRead(dirIni, "NECROMANCER", "Hardened Bones"), 
			"* While you have 7 or more Minions, your Minions gain [10-20]% increased Damage Reduction."],
		["Hungry Blood", IniRead(dirIni, "NECROMANCER", "Hungry Blood"), 
			"* When Blood Lance hits an enemy that is already lanced, it has a [10-20]% chance to fire a Blood Lance at a Nearby enemy."],
		["Plunging Darkness", IniRead(dirIni, "NECROMANCER", "Plunging Darkness"), 
			"* Bone Prison spawns a pool of Blight that deals [50-100]% bonus damage over 6 seconds"],
		["Potent Blood", IniRead(dirIni, "NECROMANCER", "Potent Blood"), 
			"* While at full Life, Blood Orbs grant [10-20] Essence."],
		["Rathmas Chosen", IniRead(dirIni, "NECROMANCER", "Rathmas Chosen"), 
			"* Whenever your Blood Skills Overpower you, gain [20-50]%[+] Attack Speed for 4 seconds."],
		["Reanimation", IniRead(dirIni, "NECROMANCER", "Reanimation"), 
			"* Your Skeletons gain increased damage while alive, up to [20-30]%[x] after 10 seconds."],
		["Serration", IniRead(dirIni, "NECROMANCER", "Serration"), 
			"* The Ossified Essence Key Passive also increases the Critical Strike Damage of your Bone Skills by 1%[+] per Essence, up to [30-40]%[+]"],
		["Shielding Storm", IniRead(dirIni, "NECROMANCER", "Shielding Storm"), 
			"* Each time that Bone Storm damages an enemy, gain a Barrier equal to [2-5]% of your Base Life for 10 seconds."],
		["Swelling Curse", IniRead(dirIni, "NECROMANCER", "Swelling Curse"), 
			"* Bone Spirit deals increased damage based on distance traveled, up to [15-25]%[x]"],
		["Torment", IniRead(dirIni, "NECROMANCER", "Torment"), 
			"* Critical Strikes with Bone Skills increase your Essence Regeneration by [20-30]%[x] for 4 seconds."],
		["Ultimate Shadow", IniRead(dirIni, "NECROMANCER", "Ultimate Shadow"), 
			"* Bone Storm and Blood Wave are also Darkness Skills, deal Shadow damage, and gain additional effects: Enemies damaged by Bone Storm take [X] Shadow damage over 2 seconds. Blood Wave desecrates the ground it travels over, dealing [X] Shadow damage over 4 seconds"],
		["Untimely Death", IniRead(dirIni, "NECROMANCER", "Untimely Death"), 
			"* Each percent of your Maximum Life you Heal beyond 100% grants you 0.5 bonus Overpower damage on your next Overpowering attack, up to a [20.0-60.0]% bonus."],
		["Damned", IniRead(dirIni, "NECROMANCER", "Damned"), 
			"* You deal [30-40]%[x] increased Shadow Damage to enemies afflicted by both Decrepify and Iron Maiden."],
		["Embalmer", IniRead(dirIni, "NECROMANCER", "Embalmer"), 
			"* Consuming a Corpse has a [20 - 30]% chance to spawn a Blood Orb."],
		["Void", IniRead(dirIni, "NECROMANCER", "Void"), 
			"* Blight's defiled area, when spawned, Pulls in enemies around the affected area."],
		["Blighted", IniRead(dirIni, "NECROMANCER", "Blighted"), 
			"* You deal [50-120%] increased damage for 6 seconds after the Shadowblight Key Passive damages enemies 10 times."],
		["Blood Getter", IniRead(dirIni, "NECROMANCER", "Blood Getter"), 
			"* Your maximum number of Skeletal Warriors is increased by 2."],
		["Blood Seeker", IniRead(dirIni, "NECROMANCER", "Blood Seeker"), 
			"* Blood Lance deals [15-25%] increased damage to its primary target per lanced enemy"],
		["Blood Soaked", IniRead(dirIni, "NECROMANCER", "Blood Soaked"), 
			"* Blood Mist leaves a trail that lasts for 4 seconds and deals [X] Shadow damage per second to enemies who stand in it. Your Movement Speed is no longer reduced while Blood Mist is active."],
		["Blood Bathed", IniRead(dirIni, "NECROMANCER", "Blood Bathed"), 
			"* Blood Surge's nova echoes again after a short delay, dealing [70-35%] less damage."],
		["Cadaverous", IniRead(dirIni, "NECROMANCER", "Cadaverous"), 
			"* Consuming a Corpse increases the damage of your next Core Skill by [5-10%], up to [25-50%]"],
		["Coldbringer", IniRead(dirIni, "NECROMANCER", "Coldbringer"), 
			"* Every 10 seconds, your Cold Skeletal Mages cast a blizzard that deals [X] Cold damage and continuously Chills enemies for 8% over 6 seconds."],
		["Fastblood", IniRead(dirIni, "NECROMANCER", "Fastblood"), 
			"* Blood Orbs reduce your Ultimate Cooldown by [0.5-1.0] seconds."],
		["Flesh Rending", IniRead(dirIni, "NECROMANCER", "Flesh Rending"), 
			"* After Decompose spawns a Corpse, gain [10-20] Essence."],
		["Hulking", IniRead(dirIni, "NECROMANCER", "Hulking"), 
			"* Your Golem has [1-4%] chance to reduce its active Cooldown by 2 seconds and a [0.5-2%] chance to spawn a Corpse each time it damages an enemy with its normal attack."],
		["Osseous", IniRead(dirIni, "NECROMANCER", "Osseous"), 
			"* Bone Storm consumes up to 8 Corpses to increase its duration by up to [X] seconds."],
		["Requiem", IniRead(dirIni, "NECROMANCER", "Requiem"), 
			"* You gain [3-5] maximum Essence per active Minion."],
		["Rotting", IniRead(dirIni, "NECROMANCER", "Rotting"), 
			"* Decompose can chain up to 2 additional targets. When Decompose spawns a Corpse, it has a [30-60%] chance to spawn a Corpse under all afflicted targets."],
		["Sacrificial", IniRead(dirIni, "NECROMANCER", "Sacrificial"), 
			"* Your Sacrifice bonuses are increased by [15-25%]"],
		["Splintering", IniRead(dirIni, "NECROMANCER", "Splintering"), 
			"* Bone Spear's primary attack makes enemies hit beyond the first Vulnerable for [1.5-2.5] seconds. Bone Shards from Bone Spear deal [50-100%] bonus damage to Vulnerable enemies and pierce them."],
		["Tidal", IniRead(dirIni, "NECROMANCER", "Tidal"), 
			"* Blood Wave fires two additional waves, each dealing [50-60]% less damage than the previous."],
		["Torturous", IniRead(dirIni, "NECROMANCER", "Torturous"), 
			"* Enemies afflicted by your Iron Maiden have a [15-25]% chance to be Stunned for 1 second when they deal direct damage."],
		["Unyielding Commander", IniRead(dirIni, "NECROMANCER", "Unyielding Commander"), 
			"* While Army of the Dead is active, your Minions gain [70-100%] Attack Speed and take 90% reduced damage."],
		["Viscous", IniRead(dirIni, "NECROMANCER", "Viscous"), 
			"* Your maximum number of Skeletal Mages is increased by 2."]
	]
	return necromancerNames
}
