#SingleInstance Force

getRogueNames()
{
dirIni := "C:\Users\marcu\Desktop\diablo\aspects.ini"
	rogueNames := [
		["Arrow Storms", IniRead(dirIni, "ROGUE", "Arrow Storms"), 
			"* Lucky Hit: Your Marksman Skills have up to a 10% chance to create an arrow storm at the target's present location, dealing [404]% Physical damage over 3 seconds. You can have up to 5 active arrow storms. (Rogue Only)"],
		["Branching Volleys", IniRead(dirIni, "ROGUE", "Branching Volleys"), 
			"* Barrage's arrows have [15-25]% chance to split into 2 arrows whenever they ricochet. (Rogue Only)"],
		["Bursting Venoms", IniRead(dirIni, "ROGUE", "Bursting Venoms"), 
			"* Lucky Hit: Critical Strikes with Poison Imbued Skills have up to a 404% chance to create a toxic pool that deals [404] Poisoning damage over 3 seconds to enemies within. While standing in the pool Poison Imbuement has no Cooldown and no Charge limit. (Rogue Only)"],
		["Corruption", IniRead(dirIni, "ROGUE", "Corruption"), 
			"* Your Imbuement Skill effects have [20-40]%[x] increased potency against Vulnerable enemies. (Rogue Only)"],
		["Cruel Sustenance", IniRead(dirIni, "ROGUE", "Cruel Sustenance"), 
			"* Explosions from the Victimize Key Passive Heal you for [404] Life for each enemy damaged, up to a maximum of [404] Life. (Rogue Only)"],
		["Elusive Menace", IniRead(dirIni, "ROGUE", "Elusive Menace"), 
			"* While you have both bonuses from the Close Quarters Combat Key Passive active, your Dodge Chance increases by [1-5]% whenever you're hit by a Close enemy. Successfully Dodging resets this bonus. (Rogue Only)"],
		["Encircling Blades", IniRead(dirIni, "ROGUE", "Encircling Blades"), 
			"* Flurry damages enemies in a circle around you and deals [8-15]%[x] increased damage. (Rogue Only)"],
		["Explosive Verve", IniRead(dirIni, "ROGUE", "Explosive Verve"), 
			"* Your Grenade Skills count as Trap Skills. Whenever you arm a Trap or drop Grenades, you gain [10-18]%[+] increased Movement Speed for 3 seconds. (Rogue Only)"],
		["Imitated Imbuement", IniRead(dirIni, "ROGUE", "Imitated Imbuement"), 
			"* Your Shadow Clones also mimic the Imbuements applied to your Skills. Casting an Imbuement Skill grants your active Shadow Clone [8-16]%[x] increased damage for 5 seconds. (Rogue Only)"],
		["Lethal Dusk", IniRead(dirIni, "ROGUE", "Lethal Dusk"), 
			"* Evading through an enemy infected by Shadow Imbuement grants Stealth for 4 seconds. Breaking Stealth with an attack grants you [1-5]% Maximum Life on Kill for 4 seconds. (Rogue Only)"],
		["Noxious Ice", IniRead(dirIni, "ROGUE", "Noxious Ice"), 
			"* Chilled enemies Poisoned by Poison Imbuement will be further Chilled for 20% per second. You deal [10-25]%[x] additional Poison damage to Frozen enemies. (Rogue Only)"],
		["Quickening Fog", IniRead(dirIni, "ROGUE", "Quickening Fog"), 
			"* You automatically drop a Smoke Grenade at the end of Dash. Dash's Cooldown is reduced by [0.25-0.35] seconds for each enemy Dazed this way, up to [0.75-1.05] seconds. (Rogue Only)"],
		["Quickening", IniRead(dirIni, "ROGUE", "Quickening"), 
			"* You automatically drop a Smoke Grenade at the end of Dash. Dash's Cooldown is reduced by [0.25-0.35] seconds for each enemy hit this way, up to [0.75- 1.05] seconds.  (Rogue Only)"], ; edge case weird, same
		["Repeating", IniRead(dirIni, "ROGUE", "Repeating"), 
			"* Rapid Fire has a [25]% chance to ricochet to another target. (Rogue Only)"],
		["Siphoned Victuals", IniRead(dirIni, "ROGUE", "Siphoned Victuals"), 
			"* Lucky Hit: Damaging a Vulnerable enemy with a Core Skill has up to a [10-20]% chance to drop a Healing Potion (Rogue Only)"],
		["Stolen Vigor", IniRead(dirIni, "ROGUE", "Stolen Vigor"), 
			"* Each stack of the Momentum Key Passive Heals you for [404] Life per second. (Rogue Only)"],
		["Surprise", IniRead(dirIni, "ROGUE", "Surprise"), 
			"* When you Evade or Shadow Step, you leave behind a cluster of exploding Stun Grenades that deal [404] total Physical damage and Stun enemies for 2 seconds. (Rogue Only)"],
		["Synergy", IniRead(dirIni, "ROGUE", "Synergy"), 
			"* Using an Agility Skill reduces the Cooldown of your next Subterfuge Skill by 20%. Using a Subterfuge Skill increases the damage of your next Agility Skill by [10-30]%[x]  (Rogue Only)"],
		["Uncanny Resilience", IniRead(dirIni, "ROGUE", "Uncanny Resilience"), 
			"* Whenever you trigger a Lucky Hit, gain [404]%[x] increased Damage Reduction for 5 seconds, up to a maximum of [404]%[x] (Rogue Only)"],
		["Uncanny Treachery", IniRead(dirIni, "ROGUE", "Uncanny Treachery"), 
			"* Dealing direct damage to a Dazed Enemy with an Agility Skill grants Stealth for 4 seconds. Breaking Stealth with an attack grants you [15-45]% Control impaired Duration Reduction for 4 seconds. (Rogue Only)"],
		["Unstable Imbuements", IniRead(dirIni, "ROGUE", "Unstable Imbuements"), 
			"* When casting an lmbuement Skill you trigger an Imbued explosion around yourself, applying the Imbuement effects and dealing [404] damage of the same type. (Rogue Only)"],
		["Volatile Shadows", IniRead(dirIni, "ROGUE", "Volatile Shadows"), 
			"* When a Dark Shroud shadow would be removed, you trigger an explosion around yourself that deals [404] Shadow damage (Rogue Only)"],
		["Bladedancer", IniRead(dirIni, "ROGUE", "Bladedancer"), 
			"* Twisting Blades orbit for a short time after they return to you, dealing [10-15%] of Twisting Blades' return damage per hit. Based on the distance the blades returned, the orbit damage increases up to [20-30%] of the return damage. (Rogue Only)"],
		["Blast Trapper", IniRead(dirIni, "ROGUE", "Blast Trapper"), 
			"* Lucky Hit: Dealing direct damage to enemies affected by your Trap Skills has up to a [30-50%] chance to make them Vulnerable for 3 seconds. (Rogue Only)"],
		["Cheat", IniRead(dirIni, "ROGUE", "Cheat"), 
			"* You take [15.0-25.0%] less damage from Crowd Controlled enemies. Whenever a Crowd Controlled enemy deals direct damage to you, gain 15%[+] Movement Speed for 2 seconds. (Rogue Only)"],
		["Energizing", IniRead(dirIni, "ROGUE", "Energizing"), 
			"* Damaging an Elite enemy with a Basic Skill generates [3 - 7] Energy. (Rogue Only)"],
		["Enshrouding", IniRead(dirIni, "ROGUE", "Enshrouding"), 
			"* Gain a free Dark Shroud shadow every 3 seconds when standing still. Each Dark Shroud shadow grants [2.0-4.0%] increased Damage Reduction. (Rogue Only)"],
		["Escape Artist", IniRead(dirIni, "ROGUE", "Escape Artist"), 
			"* Upon taking damage from surrounding enemies, you drop a Smoke Grenade and Dodge the next [2-7] attacks within 10 seconds. This effect can only occur once every 100 seconds. (Rogue Only)"],
		["Frostbitten", IniRead(dirIni, "ROGUE", "Frostbitten"), 
			"* Chilled enemies hit by your Grenade Skills have a chance equal to double your Critical Strike Chance to be instantly Frozen for 2 seconds. You deal [10-25%] increased Critical Strike Damage against Frozen enemies. (Rogue Only)"],
		["Icy Alchemist", IniRead(dirIni, "ROGUE", "Icy Alchemist"), 
			"* Lucky Hit: Damaging a Chilled or Frozen enemy with a Shadow Imbued Skill has up to a 75% chance to release an explosion that deals [404] Cold damage to the target and surrounding enemies, Chilling them for 15%. (Rogue Only)"],
		["Infiltrator", IniRead(dirIni, "ROGUE", "Infiltrator"), 
			"* Poison Trap no longer breaks Stealth and triggers no Cooldown or arm time while you are in Stealth. All Poison Traps activate when you exit Stealth and Poison Trap's Cooldown will be [5 - 8] seconds per trap placed. (Rogue Only)"],
		["Mangler", IniRead(dirIni, "ROGUE", "Mangler"), 
			"* Lucky Hit: Dealing direct damage to a Vulnerable enemy has up to a [25-45%] chance to Daze them for 2 seconds. (Rogue Only)"],
		["Opportunist", IniRead(dirIni, "ROGUE", "Opportunist"), 
			"* When you break Stealth with an attack, you drop a cluster of exploding Stun Grenades around your location that deal [404] total Physical damage and Stun enemies for 0.50 seconds (Rogue Only)"],
		["Ravager", IniRead(dirIni, "ROGUE", "Ravager"), 
			"* Shadow Step has an additional Charge. Killing an enemy with Shadow Step refunds a Charge and increases the damage of Shadow Step by [1-6%] for 2 seconds, up to [5-30%] (Rogue Only)"],
		["Ravenous", IniRead(dirIni, "ROGUE", "Ravenous"), 
			"* Killing a Vulnerable enemy grants you [50-70%] increased Energy Regeneration for 4 seconds. (Rogue Only)"],
		["Shadowslicer", IniRead(dirIni, "ROGUE", "Shadowslicer"), 
			"* When you cast Dash, a Shadow Clone is spawned at your location that also casts Dash, dealing [25-35%] of the Base damage. (Rogue Only)"],
		["Snap Frozen", IniRead(dirIni, "ROGUE", "Snap Frozen"), 
			"* Each Chilled or Frozen enemy you Evade through grants you a Barrier that absorbs 404 damage for [404] seconds, absorbing up to a maximum of [404] damage. (Rogue Only)"],
		["Toxic Alchemist", IniRead(dirIni, "ROGUE", "Toxic Alchemist"), 
			"* Lucky Hit: Damaging a Poisoned enemy with a Shadow Imbued Skill has up to a 75% chance to create a toxic explosion that applies [404] Poisoning damage over 5 seconds to the target and surrounding enemies. (Rogue Only)"],
		["Trickshot", IniRead(dirIni, "ROGUE", "Trickshot"), 
			"* Whenever Penetrating Shot damages an enemy, 2 additional arrows split off to either side. These side arrows deal [10-25%] of Penetrating Shot's Base damage and do not split. (Rogue Only)"],
		["Trickster", IniRead(dirIni, "ROGUE", "Trickster"), 
			"* Caltrops also throw a cluster of Stun Grenades that explode and deal [404] total Physical damage and Stunning enemies for 0.50 seconds. (Rogue Only)"],
		["Umbrous", IniRead(dirIni, "ROGUE", "Umbrous"), 
			"* Lucky Hit: Critical Strikes with Marksman Skills have up to a [404]% chance to grant a free Dark Shroud shadow. (Rogue Only)"],
		["Vengeful", IniRead(dirIni, "ROGUE", "Vengeful"), 
			"* Lucky Hit: Making an enemy Vulnerable has up to a [30-50%] chance to grant +3% increased Critical Strike Chance for 3 seconds, up to +9%."]
	]
	return rogueNames
}
