#SingleInstance Force

getSorcererNames()
{
dirIni := "C:\Users\marcu\Desktop\diablo\aspects.ini"
	sorcererNames := [
		["Abundant Energy", IniRead(dirIni, "SORCERER", "Abundant Energy"), 
			"* Crackling Energy has a [20-30]% chance to chain to an additional enemy."],
		["Ancient Flame", IniRead(dirIni, "SORCERER", "Ancient Flame"), 
			"* While both bonuses from the Esu's Ferocity Key Passive are active, your Attack Speed is increased by [40-50]%."],
		["Armageddon", IniRead(dirIni, "SORCERER", "Armageddon"), 
			"* An hail of Meteorites falls during Inferno, dealing [X] Fire Damage on impact. Your Meteorites Immobilize enemies for 3 seconds."],
		["Binding Embers", IniRead(dirIni, "SORCERER", "Binding Embers"), 
			"* Flame Shield lets you move unhindered through enemies. Enemies you move through while Flame Shield is active are Immobilized for [2.0-3.0] seconds."],
		["Biting Cold", IniRead(dirIni, "SORCERER", "Biting Cold"), 
			"* When you Freeze an enemy, there is a [25-35%] chance they become Vulnerable for 3 seconds."],
		["Concentration", IniRead(dirIni, "SORCERER", "Concentration"), 
			"* Your Mana Regeneration is increased by [10-20%][x] if you have not taken damage in the last 3 seconds."],
		["Conflagration", IniRead(dirIni, "SORCERER", "Conflagration"), 
			"* While channeling Incinerate, your Burning damage is increased by [20-30]%[x]"],
		["Control", IniRead(dirIni, "SORCERER", "Control"), 
			"* You deal [30-40]%[x] more damage to Immobilized, Stunned, or Frozen enemies."],
		["Efficiency", IniRead(dirIni, "SORCERER", "Efficiency"), 
			"* Casting a Basic skill reduces the Mana cost of your next Core skill by [10-20]%"],
		["Engulfing Flames", IniRead(dirIni, "SORCERER", "Engulfing Flames"), 
			"* While enemies are affected by more Damage Over Time than their total Life, you deal [30-40]%[x] increased Burning damage to them."],
		["Fortune", IniRead(dirIni, "SORCERER", "Fortune"), 
			"* Your Lucky Hit Chance is increased by [10-20]%[+] while you have a Barrier active."],
		["Frozen Memories", IniRead(dirIni, "SORCERER", "Frozen Memories"), 
			"* The Avalanche Key Passive now applies to 1 additional casts."],
		["Frozen Orbit", IniRead(dirIni, "SORCERER", "Frozen Orbit"), 
			"* Frozen Orb stays in place after reaching its destination and explodes 2 additional times for [20-30]% of its damage."],
		["Frozen Wake", IniRead(dirIni, "SORCERER", "Frozen Wake"), 
			"* While Ice Armor is active, you leave behind exploding Ice Spikes that deal [X] damage. Your Ice Spikes Chill enemies for [10%]."],
		["Overwhelming Currents", IniRead(dirIni, "SORCERER", "Overwhelming Currents"), 
			"* Unstable Currents has a [10-20]% chance to cast an additional Shock Skill."],
		["Piercing Cold", IniRead(dirIni, "SORCERER", "Piercing Cold"), 
			"* Ice Shards pierce [3-4] times, dealing [50-100]% less damage per subsequent enemy hit."],
		["Shattered Stars", IniRead(dirIni, "SORCERER", "Shattered Stars"), 
			"* Meteorites fall around Meteor, dealing [X] Fire damage on impact. Your Meteorites additionally Burn enemies they hit for [X] damage over [X] seconds."],
		["Singed Extremities", IniRead(dirIni, "SORCERER", "Singed Extremities"), 
			"* After Immobilize wears off, enemies are Slowed by [25-35]% for 4 seconds"],
		["Splintering Energy", IniRead(dirIni, "SORCERER", "Splintering Energy"), 
			"* Lightning Spear has a [11-20]% chance to spawn an additional Lightning Spear when you cast it."],
		["Static Cling", IniRead(dirIni, "SORCERER", "Static Cling"), 
			"* Your casts of Charged Bolts have a [15.0-25.0]% chance to be attracted to enemies and last 300% longer."],
		["Three Curses", IniRead(dirIni, "SORCERER", "Three Curses"), 
			"* Meteor deals [35-50]%[x] increased Critical Strike Damage against Healthy targets."],
		["Bounding Conduit", IniRead(dirIni, "SORCERER", "Bounding Conduit"), 
			"* Gain [20-25]% Movement Speed for 3 seconds after Teleporting."],
		["Frozen Tundra", IniRead(dirIni, "SORCERER", "Frozen Tundra"), 
			"* While Deep Freeze is active, exploding Ice Spikes form in the area, dealing [X] Cold damage. Your Ice Spikes have a [25-35%] increased explosion radius."],
		["Unbroken Tether", IniRead(dirIni, "SORCERER", "Unbroken Tether"), 
			"* Chain Lightning has a [25-35%] chance to chain 2 additional times."],
		["Unwavering", IniRead(dirIni, "SORCERER", "Unwavering"), 
			"* Taking direct damage has a [2-6%] chance to reset the Cooldown of one of your Defensive Skills."],
		["Charged", IniRead(dirIni, "SORCERER", "Charged"), 
			"* Collecting Crackling Energy increases your Movement Speed by [10-15%] for 4 seconds."],
		["Elementalist", IniRead(dirIni, "SORCERER", "Elementalist"), 
			"* Core or Mastery Skills cast at or above 100 Mana gain a [20.0 - 40.0%] increased Critical Strike Chance."],
		["Encased", IniRead(dirIni, "SORCERER", "Encased"), 
			"* While Deep Freeze is active, you restore [10-20%] of your Maximum Life and Mana per second."],
		["Everliving", IniRead(dirIni, "SORCERER", "Everliving"), 
			"* You take [20-25%] less damage from Crowd Controlled or Vulnerable enemies."],
		["Flamewalker", IniRead(dirIni, "SORCERER", "Flamewalker"), 
			"* Coming in contact with your Firewall grants you [15-25%] Movement Speed for 4 seconds."],
		["Frostblitz", IniRead(dirIni, "SORCERER", "Frostblitz"), 
			"* Frost Nova gains an additional Charge, but the Cooldown per Charge is increased by [40-30%]."],
		["Glacial", IniRead(dirIni, "SORCERER", "Glacial"), 
			"* When you cast Blizzard, it will periodically spawn exploding Ice Spikes that deal [X] damage. Your Ice Spikes deal [20-30%] increased damage to Frozen enemies."],
		["Gravitational", IniRead(dirIni, "SORCERER", "Gravitational"), 
			"* Ball Lightning orbits around you, but its damage is decreased by [20-10%]."],
		["Incendiary", IniRead(dirIni, "SORCERER", "Incendiary"), 
			"* Lucky Hit: Burning Damage has up to a [5-10%] chance to restore 10 Mana."],
		["Mage Lord", IniRead(dirIni, "SORCERER", "Mage Lord"), 
			"* The Vyr's Mastery Key Passive's Damage Reduction is increased by [20-30%] for each Close enemy, up to [60-90%]."],
		["Prodigy", IniRead(dirIni, "SORCERER", "Prodigy"), 
			"* Using a Cooldown restores [15-25] Mana."],
		["Recharging", IniRead(dirIni, "SORCERER", "Recharging"), 
			"* Each time Chain Lightning bounces off you, gain [4-6] Mana."],
		["Serpentine", IniRead(dirIni, "SORCERER", "Serpentine"), 
			"* You may have 1 additional Hydra active, but Hydra's duration is reduced by [30-20%]."],
		["Shattered", IniRead(dirIni, "SORCERER", "Shattered"), 
			"* Explosions from the Shatter Key Passive deal [30-40%] increased damage if enemies die while Frozen."],
		["Snowguard", IniRead(dirIni, "SORCERER", "Snowguard"), 
			"* While within your own Blizzard, you take [20.0-25.0%] less damage."],
		["Snowveiled", IniRead(dirIni, "SORCERER", "Snowveiled"), 
			"* Casting Ice Armor makes you Unstoppable for [2.0-3.0] seconds."],
		["Stable", IniRead(dirIni, "SORCERER", "Stable"), 
			"* While Unstable Currents is not active, your Shock Skills have a [5-10%] chance to trigger a free cast from it."],
		["Storm Swell", IniRead(dirIni, "SORCERER", "Storm Swell"), 
			"* You deal [11-20%] increased damage to Vulnerable enemies while you have a Barrier."]
	]
	return sorcererNames
}
