getClassArray()
{
	;[maxValue, infoText]
	;maxValue not really needed
	
	classArray := [
		[7.3, "Dexterity"],
		[7.3, "Willpower"],
		[7.3, "Strength"],
		[7.3, "Intelligence"],
		[14, "Healing Received"],
		[2, "Ranks of the Outburst Passive"],
		[2, "Ranks of the Slaying Strike Passive"],
		[2, "Ranks of the Brute Force Passive"],
		[2, "Ranks of the Nature's Reach Passive"],
		[2, "Ranks of the Crushing Earth Passive"],
		[2, "Ranks of the Natural Disaster Passive"],
		[2, "Ranks of the Toxic Claws Passive"],
		[2, "Ranks of the Terror Passive"],
		[2, "Ranks of the Compound Fracture Passive"],
		[2, "Ranks of the Hellbent Commander Passive"],
		[2, "Ranks of the Deadly Venom Passive"],
		[2, "Ranks of the Malice Passive"],
		[2, "Ranks of the Hoarfrost Passive"],
		[2, "Ranks of the Icy Touch Passive"],
		[2, "Ranks of the Inner Flames Passive"],
		[2, "Ranks of the Shocking Impact Passive"],
		[3, "Ranks of Hammer of the Ancients"],
		[3, "Ranks of Upheaval"],
		[3, "Ranks of Charge"],
		[3, "Ranks of Iron Skin"],
		[3, "Ranks of Rallying Cry"],
		[3, "Ranks of War Cry"],
		[3, "Ranks of Landslide"],
		[3, "Ranks of Lightning Storm"],
		[3, "Ranks of Boulder"],
		[3, "Ranks of Earthen Bulwark"],
		[3, "Ranks of Ravens"],
		[3, "Ranks of Wolves"],
		[2, "Ranks of All Curse Skills"],
		[3, "Ranks of Blight"],
		[3, "Ranks of Blood Lance"],
		[3, "Ranks of Bone Spirit"],
		[3, "Ranks of Decrepify"],
		[2, "Ranks of All Imbuement Skills"],
		[3, "Ranks of Flurry"],
		[3, "Ranks of Penetrating Shot"],
		[3, "Ranks of Cold Imbuement"],
		[3, "Ranks of Dash"],
		[3, "Ranks of Shadow Step"],
		[2, "Ranks of All Mastery Skills"],
		[3, "Ranks of Chain Lightning"],
		[3, "Ranks of Frozen Orb"],
		[3, "Ranks of Firewall"],
		[3, "Ranks of Hydra"],
		[3, "Ranks of Lightning Spear"],
		[2, "Ranks of the Wallop Passive"],
		[2, "Ranks of the Cut to the Bone Passive"],
		[2, "Ranks of the No Mercy Passive"],
		[2, "Ranks of the Wild Impulses Passive"],
		[2, "Ranks of the Resonance Passive"],
		[2, "Ranks of the Call of the Wild Passive"],
		[2, "Ranks of the Gloom Passive"],
		[2, "Ranks of the Coalesced Blood Passive"],
		[2, "Ranks of the Tides of Blood Passive"],
		[2, "Ranks of the Amplify Damage Passive"],
		[2, "Ranks of the Exploit Passive"],
		[2, "Ranks of the Weapon Mastery Passive"],
		[2, "Ranks of the Conjuration Mastery Passive"],
		[2, "Ranks of the Glass Cannon Passive"],
		[2, "Ranks of the Endless Pyre Passive"],
		[2, "Ranks of All Brawling Skills"],
		[3, "Ranks of Rend"],
		[3, "Ranks of Whirlwind"],
		[3, "Ranks of Death Blow"],
		[3, "Ranks of Kick"],
		[3, "Ranks of Rupture"],
		[2, "Ranks of All Companion Skills"],
		[3, "Ranks of Pulverize"],
		[3, "Ranks of Shred"],
		[3, "Ranks of Cyclone Armor"],
		[3, "Ranks of Hurricane"],
		[3, "Ranks of Trample"],
		[2, "Ranks of All Defensive Skills"],
		[2, "Ranks of All Macabre Skills"],
		[3, "Ranks of Sever"],
		[3, "Ranks of Blood Mist"],
		[3, "Ranks of Corpse Explosion"],
		[3, "Ranks of Iron Maiden"],
		[2, "Ranks of All Subterfuge Skills"],
		[3, "Ranks of Barrage"],
		[3, "Ranks of Poison Imbuement"],
		[3, "Ranks of Concealment"],
		[3, "Ranks of Poison Trap"],
		[3, "Ranks of Smoke Grenade"],
		[3, "Ranks of Fireball"],
		[3, "Ranks of Charged Bolts"],
		[3, "Ranks of Ball Lightning"],
		[3, "Ranks of Flame Shield"],
		[3, "Ranks of Ice Armor"],
		[3, "Ranks of Meteor"],
		[2, "Ranks of the Counteroffensive Passive"],
		[2, "Ranks of the Heavy Handed Passive"],
		[2, "Ranks of the Tough as Nails Passive"],
		[2, "Ranks of the Stone Guard Passive"],
		[2, "Ranks of the Envenom Passive"],
		[2, "Ranks of the Defiance Passive"],
		[2, "Ranks of the Quickshift Passive"],
		[2, "Ranks of the Death's Reach Passive"],
		[2, "Ranks of the Imperfectly Balanced Passive"],
		[2, "Ranks of the Evulsion Passive"],
		[2, "Ranks of the Fueled by Death Passive"],
		[2, "Ranks of the Frigid Finesse Passive"],
		[2, "Ranks of the Impetus Passive"],
		[2, "Ranks of the Permafrost Passive"],
		[2, "Ranks of the Elemental Dominance Passive"],
		[2, "Ranks of the Devouring Blaze Passive"],
		[2, "Ranks of All Weapon Mastery Skills"],
		[3, "Ranks of Double Swing"],
		[3, "Ranks of Challenging Shout"],
		[3, "Ranks of Ground Stomp"],
		[3, "Ranks of Leap"],
		[3, "Ranks of Steel Grasp"],
		[2, "Ranks of All Wrath Skills"],
		[3, "Ranks of Tornado"],
		[3, "Ranks of Blood Howl"],
		[3, "Ranks of Debilitating Roar"],
		[3, "Ranks of Rabies"],
		[3, "Ranks of Poison Creeper"],
		[2, "Ranks of All Corpse Skills"],
		[3, "Ranks of Bone Spear"],
		[3, "Ranks of Blood Surge"],
		[3, "Ranks of Bone Prison"],
		[3, "Ranks of Corpse Tendrils"],
		[2, "Ranks of Alll Agility Skills"],
		[3, "Ranks of Rapid Fire"],
		[3, "Ranks of Twisting Blades"],
		[3, "Ranks of Caltrops"],
		[3, "Ranks of Dark Shroud"],
		[3, "Ranks of Shadow Imbuement"],
		[2, "Ranks of All Conjuration Skills"],
		[3, "Ranks of Ice Shards"],
		[3, "Ranks of Incinerate"],
		[3, "Ranks of Blizzard"],
		[3, "Ranks of Frost Nova"],
		[3, "Ranks of Ice Blades"],
		[3, "Ranks of Teleport"]
	]
	return classArray
}